# Generated by Django 3.2.2 on 2021-05-17 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=250)),
                ('file', models.FileField(upload_to='files')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('check_date', models.DateField()),
                ('assent_date', models.DateField()),
                ('present_date', models.DateField()),
                ('accept_date', models.DateField()),
                ('aontract_date', models.DateField()),
                ('ip_address', models.CharField(max_length=15)),
                ('judges', models.ManyToManyField(related_name='judge', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
