# Generated by Django 3.2.2 on 2021-05-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='accept_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='aontract_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='assent_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='check_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='ip_address',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='present_date',
            field=models.DateField(null=True),
        ),
    ]
