# Generated by Django 3.2.2 on 2023-08-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='exam',
        ),
        migrations.AddField(
            model_name='schedule',
            name='exam_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='exam_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='exam_location',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='exam_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='exam_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='building',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='plato',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
