# Generated by Django 3.2.2 on 2021-05-19 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0002_auto_20210518_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='file',
            field=models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
