# Generated by Django 3.2.2 on 2023-08-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('projection', '0002_auto_20230806_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date_of_week', models.PositiveSmallIntegerField(choices=[(0, 'sat'), (1, 'sun'), (2, 'mon'), (3, 'tue'), (4, 'wed'), (5, 'thu'), (6, 'fri')])),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
