# Generated by Django 3.2.2 on 2021-05-28 12:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projection', '0003_alter_proposal_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='file',
            field=models.FileField(null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='judges',
            field=models.ManyToManyField(null=True, related_name='judge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='members',
            field=models.ManyToManyField(null=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='unique_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
