# Generated by Django 3.2.2 on 2021-06-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projection', '0005_proposal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='status',
        ),
    ]
