# Generated by Django 3.2.2 on 2021-06-10 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projection', '0006_remove_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='judges',
            field=models.ManyToManyField(related_name='judge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='members',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
