# Generated by Django 3.2.2 on 2021-05-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210510_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Specialty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
