# Generated by Django 3.2.2 on 2021-05-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_specialty_profile_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Member'), (3, 'Judge')], help_text='is Admin , Leader , Member or Judge'),
        ),
    ]
