# Generated by Django 3.2.2 on 2021-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'member'), (3, 'judge')], help_text='is Admin , Leader , Member or Judge'),
        ),
    ]
