# Generated by Django 3.2.2 on 2021-05-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders'),
        ),
    ]
